# Generated by Django 4.0.3 on 2022-03-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        # need two scripts to insert and for undoing migration #
        migrations.RunSQL("""
                            INSERT INTO store_collection (title)
                            VALUES ('collection1')
                          """,
                          """
                            DELETE FROM store_collection
                            WHERE title='collection1'
                          """)
    ]
